version: '3.4'

services:
  bloginsecure:
    image: ${DOCKER_REGISTRY}bloginsecure
    build:
      context: .
      dockerfile: BlogInsecure/Dockerfile

  admin.api:
    image: ${DOCKER_REGISTRY}adminapi
    build:
      context: .
      dockerfile: Services/Admin.Api/Dockerfile

  blog.api:
    image: ${DOCKER_REGISTRY}blogapi
    build:
      context: .
      dockerfile: Services/Blog.Api/Dockerfile

  sql.data:
    image: mssql-linux
    build:
      context: .
      dockerfile: Database/Dockerfile
